name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Deploy when you push to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./      # root folder
          destination_branch: gh-pages
          user_name: github-actions
          user_email: github-actions@github.com
